### ISSUE TITLE
Test documentation

### ISSUE THREAD

**Issue by kench** [concerto/concerto-frontend#16]
How do I execute the concerto-frontend tests?  There appears to be some test fixtures in this repository, but I haven't had the foggiest idea on how to run them.

**Comment by gbprz** [comment]
The test folder is used for standalone development as mentioned in the updated readme 535f07f436ab57ebe0c0d49c8ca21e3871f11bdf. It's purpose is to mimic the usual setup.json, contents.json, and other assets received by Concerto.

The documentation requested in #14 is still needed though.
