### ISSUE TITLE
Create build process

### ISSUE THREAD

**Issue by bamnet** [concerto/concerto-frontend#2]
We should have a build step which minifies / vulcanizes the frontend into one or two includes.

**Comment by gbprz** [comment]
d76fcead6907b083afaabf93b2c829c0c3b51d38 just added a Ruby Gem with the vulcanized frontend code. I'll keep an eye open for any possible improvements, but let me know if we can take this any further. 

I've also opened a branch under core Concerto here: https://github.com/concerto/concerto/tree/polymerFrontend

It's just the start, but it simply replaces the frontend screens show view with a plugin hook to include the new vulcanized frontend partial from the Ruby Gem. If this isn't the approach we should take, let me know and maybe we can work something else out.

**Comment by kench** [comment]
It sounds sensible to me.  Would a Makefile that runs the commands be useful?

Unless anyone knows of better methods of packaging this (there are no public ones that I'm aware of), this is going to do for now.
