### ISSUE TITLE
Cannot read property 'j' of undefined locks fronted up

### ISSUE THREAD

**Issue by barrct** [concerto/concerto-frontend#24]
Uncaught TypeError: Cannot read property 'j' of undefined
frontend.js:64

Windows 7 Pro
24G ram
Xeon processors
Chrome 43.0.2357.134
This happens during the preview while setting up the UI for use.

**Comment by gbprz** [comment]
Try using the latest frontend gem (0.0.4 if your source is RubyGems). Support for Firefox appears to be working now since we've migrated from Polymer 0.5 to 1.0.
