### ISSUE TITLE
this.Ec is undefined

### ISSUE THREAD

**Issue by barrct** [concerto/concerto-frontend#25]
TypeError: this.Ec is undefined
frontend.js:64:298

Windows 7 Pro
24G ram
Xeon
Firefox 39.0
This happens on page load / reload randomly.

**Comment by gbprz** [comment]
Try using the latest frontend gem (0.0.4 if your source is RubyGems). Support for Firefox appears to be working now since we've migrated from Polymer 0.5 to 1.0.
