### ISSUE TITLE
Text field sizing/spacing

### ISSUE THREAD

**Issue by augustf** [concerto/concerto-frontend#37]
The canonical BBC RSS feed still looks a bit odd -- still like one big paragraph. This isn't particularly unique to the new frontend -- the sizing spacing of dynamic content here has long been an issue.

![screen shot 2015-08-23 at 9 50 45 pm](https://cloud.githubusercontent.com/assets/12512/9431674/6c24c7c4-49e4-11e5-85c3-d635aeecc759.png)

**Comment by augustf** [comment]
For reference, there is the same feed on the old frontend over at nightly.concerto-signage.org (which is not exactly nightly
![screen shot 2015-08-25 at 1 37 17 pm](https://cloud.githubusercontent.com/assets/12512/9474397/84ae2092-4b2e-11e5-999d-85d4d958abef.png)
):

**Comment by gbprz** [comment]
Took a pass at this in #40. Let me know if there are any other strange cases where content isn't displaying / sized properly.

**Comment by augustf** [comment]
Here's the latest. 
![screen shot 2015-09-09 at 3 26 13 pm](https://cloud.githubusercontent.com/assets/12512/9771936/2f8b6de2-5707-11e5-94a8-b7e541fedc77.png)
