### ISSUE TITLE
Don't refresh repeat content on the frontend (Concerto #550)

### ISSUE THREAD

**Issue by augustf** [concerto/concerto-frontend#38]
Per https://github.com/concerto/concerto/issues/550, content should not be re-loaded when it comes after itself in sequence.

**Comment by smaddock** [comment]
Any progress on this one? We have some screens we'd like to only display a single web page (iframe)... the max 100s refresh is quite distracting.

**Comment by mfrederickson** [comment]
@smaddock is it fading in and out?  I think you can change the two field transition settings to "replace" which would definitely make it much less noticable.  https://github.com/concerto/concerto/wiki/Field-Configuration

**Comment by smaddock** [comment]
@mfrederickson Already done that... unfortunately the site we're framing has a slow, JS heavy dynamic load that refreshes each time.

**Comment by mfrederickson** [comment]
@smaddock this should be fixed when #74 gets merged.  If you want to try it in the meantime, let me know how it works out for you.

**Comment by mfrederickson** [comment]
Currently, when a duplicate comes up, the system ignores it and waits the original content's duration before trying again.  This change is not good when you have a single video (or audio) on a feed.  So perhaps this feature should be enabled or disabled by a field parameter?

**Comment by smaddock** [comment]
@mfrederickson Sure... an iFrame or vid on loop doesn't have a duration.
