### ISSUE TITLE
Frontend shows black screen

### ISSUE THREAD

**Issue by andrey-sw** [concerto/concerto-frontend#46]
Concerto Version: 2.3.0.
ConcertoFrontend via rubygems Gem version: 0.0.8

http://mysite/frontend/1

Google Chrome 45.0.2454.85 m - OK

FireFox 40.0.3 (webobjects is enabled) - Black Screen
in console 1 warn and 1 error
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create 1:215:0
TypeError: this.$ is undefined 1:8948:8

IE11 - Black Screen

**Comment by gbprz** [comment]
@andrey-sw I was able to reproduce this, try disabling the browser's web components support under the about:config page: https://developer.mozilla.org/en-US/docs/Web/Web_Components

Type about:config in your address bar, then search for 'webcomponents' and make sure it's set to 'false'. When I tried toggling this to true, I got the black screen as well.

**Comment by bamnet** [comment]
I'm surprised turning on native webcomponent support breaks things.

**Comment by gbprz** [comment]
I checked to see if anyone else was having this issue and I came across this: https://www.polymer-project.org/1.0/resources/compatibility.html

"Firefox currently supports some of the web components behind a flag. Polymer does not work correctly with this flag enabled, because of an incompatibility with the web components polyfills."

**Comment by augustf** [comment]
As I understand it, there's no real agreement on what "Web components" is going to really comprise, and as usual Mozilla is striking off in their own direction. In our tests with Polymer .5, the polyfills didn't work cross-browser at all -- leaving the frontend only working under recent Chrome versions. The frontend with Polymer 1.0 at least works in the few current browsers I've played with.

**Comment by andrey-sw** [comment]
in add
If you open a tab (http://mysite/frontend/1) and make breakpoint the debugger on the line 8948, refresh, then open a new tab(http://mysite/frontend/1) and wonder - it works
if continue 1 tab - 2 tab - refresh -> black screen

**Comment by mfrederickson** [comment]
In my testing #47 fixed this (TypeError: this.$ is undefined 1:8948:8) for both IE and firefox, so the screen works and is no longer blank.  However, the mutating warning still shows in the console (in firefox).

**Comment by augustf** [comment]
@andrey-sw Did any of these steps, the fix, or running asset precompile help you?
