### ISSUE TITLE
not detecting change in template/position/field/configs changes

### ISSUE THREAD

**Issue by mfrederickson** [concerto/concerto-frontend#50]
The screen did not reload when a field config was changed, a field' style was changed, a new field was added, nor when the background image was changed.  We generate a header which indicates when anything screen/template/field/position changes and send it with each piece of content:

https://github.com/concerto/concerto/blob/master/app/controllers/frontend/contents_controller.rb#L47

But the new frontend isn't looking at it.  This same indicator is sent (I believe) as the etag when the setup.json is sent.  

What do you think about changing the frontend from polling the setup.json every 8 seconds, to just checking that header each time it gets a piece of content?

**Comment by gbprz** [comment]
This sounds more efficient than polling the setup.json. Seems like it can be handled here then: https://github.com/concerto/concerto-frontend/blob/master/concerto-field.html#L125
Let me know if you have any other thoughts though.

**Comment by mfrederickson** [comment]
Probably so. I was thinking that the concerto-field would raise an event when it detected that the screen needed reloaded and the concerto-screen would handle it.
