### ISSUE TITLE
multiple divs with same id

### ISSUE THREAD

**Issue by mfrederickson** [concerto/concerto-frontend#51]
![image](https://cloud.githubusercontent.com/assets/473165/10354333/9016d9fc-6d0b-11e5-921c-a75f358ea664.png)

**Comment by bamnet** [comment]
If I'm reading the DOM correctly, these repeat div IDs are in the Shadow DOM of concerto-field elements.    Duplicative IDs should be permitted there as the Shadow DOM protects the scope.

**Comment by mfrederickson** [comment]
I was looking at inspect element in the Dev tools...  doesn't that show the regular Dom?
