### ISSUE TITLE
Frontend breaks when Concerto is deployed to a sub-URI

### ISSUE THREAD

**Issue by mikldt** [concerto/concerto-frontend#57]
The frontend does not appear to work when Concerto is deployed somewhere other than the root path of the domain.

Setup: concerto is deployed to a sub-URI, as https://example.com/concerto. I'm using concerto_frontend-0.2.0.

Symptoms:
* Black Screen
* Developer tools show a 404 on https://example.com/frontend/4/setup.json, (when it should have requested https://example.com/concerto/frontend/4/setup.json, as the actual frontend is accessed at http://dev.mikldt.net/concerto/frontend/4)

The cause seems to be that URLs in the app are generated with a leading / and appended to a baseUrl variable. baseUrl is set to an empty string [in concerto-screen.html, line 70](https://github.com/concerto/concerto-frontend/blob/f6a4ac7b35f06a085d55cf7feca6dd0e79384992/concerto-screen.html#L70). When I changed this to my sub-URL ("/concerto") by hacking the generated assets, setup.json was loaded successfully.

It would be ideal if the correct URL could be auto-detected in js (since the javascript should know the current URL) or included in the _frontend.html to be passed to the javascript. Alternately, it could go in a config somewhere. Unfortunately I don't think I have the polymer expertise to pull this off myself right now.

**Comment by augustf** [comment]
It may also be a good idea to document the steps for getting Rails to serve sub-uri's (in both dev and prod), since some folks on the mailing list have reported issues with that. I forget which iteration of awful hacks we're on to make that work.

**Comment by gbprz** [comment]
Looks like we didn't set the base-url attribute on our concerto-screen element. We have it set in the demo.html example but didn't add anything to the Ruby Gem's _frontend.html partial. I agree we should have it automatically populated, like the screen-id and preview attributes. Any ideas if this can be done with the Rails root url, a config/env variable, or should I take the javascript approach?

**Comment by mikldt** [comment]
Oh very cool, I didn't realize you could just set it on the element like that. Putting it in the _frontend.html partial sounds like the most straightforward approach, since Rails will already know the URL root.

The ruby variable you need to access is:
```ruby
Rails.application.config.relative_url_root
```

It will be blank for normal deployments, and look like "/directory" for sub-URI deployments

@augustf, the two steps required to get sub-URIs working seem to be:
* setting the rails env var RAILS_RELATIVE_URL_ROOT while precompiling assets, and
* setting the relative_url_root for the actual server (using passenger's server config "passenger_base_uri" should do this for you)

I've documented that first part in Concerto's installation instructions wiki page.

**Comment by mfrederickson** [comment]
@gbprz I looked at this and it's going to be more than just changing the base-url.  That does solve the problem mentioned here for the setup.json, but it breaks all of the graphic content because that element prepends the base-url to the url fetched from the content.json which already has that relative root url in it from the url_helper.  So I'm not sure how to fix this without breaking it when polyserved from the demo page, because we will need the base-url if it is actually pointing to a concerto site because that wont be in a relative root url...
