### ISSUE TITLE
investigate possible memory leaks

### ISSUE THREAD

**Issue by mfrederickson** [concerto/concerto-frontend#62]
When the frontend initially started on a RPi2 using iceweasel, it reported a memory usage of around 15%, after 5 days iceweasel showed a memory consumption of around 41%.  Killing iceweasel and restarting it, it came back up at around 15%.  The screen contained a single feed with a single piece of htmltext content.

**Comment by gbprz** [comment]
This seems to be a result of my messy cleanup with events and nodes in Polymer. I ran a quick test using Chrome's memory profiling tools and here are my results:

![screenshot - 03192016 - 11 48 18 am](https://cloud.githubusercontent.com/assets/3246274/13899613/fed3b0d4-edc8-11e5-8e2e-340cb8e63463.png)

I forced garbage collection around 60 and 120 seconds. Each dip in the heap memory should correspond to automatic garbage collection or one of my forced attempts. What appears to be bad is the general increase in memory allocation, even after a dip. The DOM node count (green) and listeners (orange) also never return anywhere close to the baseline with garbage collection which is a little strange too.  

Overall, it seems that the steady increase in heap size, nodes, and listeners are a concern. @bamnet if you get a chance, would you mind reviewing this post and letting me know if I am interpreting this correctly?

I should probably run a longer test, but it seems that a bunch of people have run into browser crashes. If anything, I can try to make some changes and run a similar test to compare with the results posted here.

**Comment by mfrederickson** [comment]
This no longer appears to be a problem based on our experience with our signs running on the Pi.
