### ISSUE TITLE
time display off

### ISSUE THREAD

**Issue by mfrederickson** [concerto/concerto-frontend#63]
Two people posted a similar problem on the forum:  

>I installed version 2.3.2 yesterday (completely fresh install, not an upgrade) and even with the timezone properly set the time is off by 5 hours (I need it to be eastern std time - and 5 hours is the difference - I think, so it seems to me that it is not taking into account the local time zone setting).

**Comment by gbprz** [comment]
I setup a fresh install and noticed the default for screens is GMT UTC+0

After editing the screen and changing it to EST, the screen refreshed and displayed the proper time. I'm curious to see if this is still an issue for anyone.
