### ISSUE TITLE
Content refresh timing

### ISSUE THREAD

**Issue by snoop168** [concerto/concerto-frontend#71]
I need the content to refresh more often. It seems like there is about a 2 minute delay on new content getting to the frontend. Is there a setting that can be changed? In my case its an updated RSS feed, so its not a "new" piece of content just and updated version of it... 

If there is a simple delay value set in the code somewhere that I can modify on my setup can someone point me to it, I've been looking but cant find it.

**Comment by mfrederickson** [comment]
If I recall correctly, the dynamic content refresh cycle is 5 minutes- I think there is a delay entry in the config portion of the database record set to 300.  But that's just for refreshing the content itself.  In terms of displaying it on the screen, I think that the content to display (the id's for them) is cached in an array which would need to be exhausted before it queries the database for more content-- so that might have something to do with it also.  

I'm curious what your use case is here-- why do you need it so quickly?

**Comment by snoop168** [comment]
I'm pulling live police calls out of our database for display to our personnel in common areas. If the calls are 4 minutes old by the time they see it, its not as good as seeing it immediately.

**Comment by snoop168** [comment]
do you know approximately where in the frontend it looks at the array and looks to be exhausted? I just wonder if I could alter a bit: (to be exhausted OR have a max time since last update)... I'm not sure if updating before its been exhausted will cause some content to show over and over while others not show up at all though...?

**Comment by mfrederickson** [comment]
Offhand, I can't recall... I'd have to read through the code again...

**Comment by mfrederickson** [comment]
@snoop168 when the screen starts up it first requests its setup information: https://github.com/concerto/concerto-frontend/blob/master/concerto-field.html#L92
```
{
  "id": 1,
  "name": "Sample Screen",
  "time_zone": "America/New_York",
  "template": {
    "id": 2,
    "name": "Waves",
    "path": "/frontend/1/templates/2.jpg",
    "css_path": null,
    "positions": [
      {
        "id": 5,
        "style": "font-family:Frobisher, sans-serif; font-size:0.8em; font-weight:bold; ",
        "top": "0.009",
        "left": "0.046",
        "bottom": "0.816",
        "right": "0.641",
        "field_contents_path": "/frontend/1/fields/1/contents.json",
        "field": {
          "id": 1,
          "name": "Graphics",
          "config": {
            "entry_transition": "replace",
            "exit_transition": "replace"
          }
        }
      },
      {
        "id": 6,
        "style": "font-family:Frobisher, sans-serif;",
        "top": "0.009",
        "left": "0.712",
        "bottom": "0.809",
        "right": "0.967",
        "field_contents_path": "/frontend/1/fields/3/contents.json",
        "field": {
          "id": 3,
          "name": "Text",
          "config": {}
        }
      },
      {
        "id": 7,
        "style": "font-family:Frobisher, sans-serif; font-size:0.8em; font-weight:bold;",
        "top": "0.858",
        "left": "0.691",
        "bottom": "0.975",
        "right": "0.938",
        "field_contents_path": "/frontend/1/fields/5/contents.json",
        "field": {
          "id": 5,
          "name": "Time",
          "config": {
            "entry_transition": "replace",
            "exit_transition": "replace"
          }
        }
      }
    ]
  }
}
```

The next thing the screen does is request content for each of the fields.  I can see from the above, that field 3 is the text field where RSS is shown.  
https://github.com/concerto/concerto-frontend/blob/master/concerto-field.html#L172
![image](https://cloud.githubusercontent.com/assets/473165/23538084/077ae1b4-ff7d-11e6-9951-f9956be597ea.png)
There were actually 72 pieces of content in that feed above.

So then the frontend is going to cycle through that content for that field until it gets to the end.  Then it will query for more.  

So what you want to happen is that whenever an RSS feed gets updated (it's typically a 5 minute cycle, I think) you want it to clear the list for any fields that display RSS and refetch the list?  This could cause some RSS content to never get displayed (depending upon how many items are in the list and how long they display for).

It sounds like what you might be looking for is some kind of vertical scrolling area that bumps up and adds the latest call as they come in.  What does the data in your rss feed of police calls look like?

**Comment by mfrederickson** [comment]
Closing in deference to #77.
