### ISSUE TITLE
Browser Caching

### ISSUE THREAD

**Issue by snoop168** [concerto/concerto-frontend#72]
I created a new field and made it type "Text". I added content to it but the screen never updates it. I think the problem is related to the web browser caching the content for the feed. I went into another tab and went to the url http://server/frontend/[screen]/fields/[fieldid]/contents.json and it displayed outdated data... I performed a regular refresh (`F5`) and it remained the same. I performed a `SHIFT+F5` and it refreshed the content and the tab running my screen eventually refreshed the field with the new content.

Just want to add - maybe this is the reason, not really sure on the logistics of browser caching -- my content is not changing much at the moment. The only thing that's actually changing is a timestamp within the content which just shows when the last time the RSS feed data was pulled. Could it be seeing the same exact number of bytes and thinking there was no change in content?

**Comment by mfrederickson** [comment]
@snoop168 I believe this should be resolved with concerto/concerto#1398 (when 2.3.5 is released).  If you find otherwise, please reopen or open a new ticket.
